# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-23 23:07
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('video_description', models.CharField(blank=True, max_length=256)),
                ('short_description', models.CharField(blank=True, max_length=256)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('location', models.CharField(blank=True, max_length=128)),
                ('open_roles', models.IntegerField(blank=True)),
                ('profile_image_external', models.CharField(blank=True, max_length=256)),
                ('job_board_external', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('upload', models.FileField(blank=True, upload_to='uploads/')),
                ('external_src', models.CharField(blank=True, max_length=256)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('type', models.CharField(blank=True, max_length=64)),
                ('file_type', models.CharField(blank=True, max_length=32)),
                ('size', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(blank=True, max_length=64)),
                ('first_name', models.CharField(blank=True, max_length=64)),
                ('last_name', models.CharField(blank=True, max_length=64)),
                ('email', models.CharField(blank=True, max_length=128)),
                ('location', models.CharField(blank=True, max_length=128)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('screen_width', models.IntegerField(blank=True)),
                ('verification', models.CharField(blank=True, max_length=64, null=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoresume.User_Info'),
        ),
    ]
