# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-26 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoresume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='user_info',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
