# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-27 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoresume', '0002_auto_20161226_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='profile_image_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
