# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-28 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoresume', '0003_auto_20161227_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='phone_number',
            field=models.CharField(blank=True, default=0, max_length=32),
            preserve_default=False,
        ),
    ]
