# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-28 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoresume', '0004_auto_20161228_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='personal_website_url',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
