# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-28 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoresume', '0005_user_info_personal_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
