# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-30 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoresume', '0007_blocked_company_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
