# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-30 19:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoresume', '0008_user_info_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoresume.User_Info')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoresume.Role')),
            ],
        ),
    ]
