# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-30 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoresume', '0009_role_sub_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='welcome_message',
            field=models.BooleanField(default=True),
        ),
    ]
