# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-02 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoresume', '0010_user_info_welcome_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='help_requested',
            field=models.BooleanField(default=False),
        ),
    ]
